#!/bin/sh
# bundle:  group files into distribution package
# (from section 3.9)

echo '# To unbundle, sh this file'
for i
do
	echo "echo $i >&2"
	echo "cat >$i <<'End of $i'"
	cat $i
	echo "End of $i"
done
